### ISSUE TITLE
Error 500 - possibly due to missing B-year

### ISSUE THREAD

**Issue by quinnphil** [cassiofb-dev/fide-api#2]
Looks like missing B-year is returning Error 500 - FUNCTION_INVOCATION_FAILED.

Some examples from the Fide Chess Olympiad 2024:
https://ratings.fide.com/profile/11305924
https://ratings.fide.com/profile/16700309
https://ratings.fide.com/profile/17700213
https://ratings.fide.com/profile/241000013 (also missing World Rank (All players) - but not sure if this is also an issue)
https://ratings.fide.com/profile/6100678

**Comment by cassiofb-dev** [comment]
Hi @quinnphil , good night! The Olympiad was an awesome event!

It was an issue with missing data on some profiles that I just fixed. Can you confirm it's working now?

https://fide-api.vercel.app/player_info/?fide_id=241000013&history=false

**Comment by quinnphil** [comment]
Amazing - thank you @cassiofb-dev.  
Confirmed as working for all examples.

The Olympiad was indeed an awesome event.  That Gukesh v. Wei Li game was incredible.
